# NumPy exercises

In [1]:
import numpy as np

print(np.__version__)

1.21.5


## Array creation

### Create a numpy array of size 10, filled with zeros

In [8]:
zeros = np.zeros(10)
print(zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


## Create a numpy array with values ranging from 10 to 49

In [9]:
np.arange(10,50)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

## Create a numpy matrix of 2*2 integers, filled with ones.

In [14]:
np.ones([2,2], dtype=np.int)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_18388\2225746612.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([2,2], dtype=np.int)


array([[1, 1],
       [1, 1]])

## Create a numpy matrix of 3*2 float numbers, filled with ones

In [15]:
np.ones([3,2], dtype = np.float)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_18388\4028849323.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([3,2], dtype = np.float)


array([[1., 1.],
       [1., 1.],
       [1., 1.]])

## Given the X numpy array, create a new numpy array with the same shape and type as X, filled with ones

In [16]:
x = np.arange(4, dtype=np.int)
np.ones_like(x)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_18388\429588936.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.arange(4, dtype=np.int)


array([1, 1, 1, 1])

## Given the X numpy matrix, create a new numpy matrix the same shape and type as X, filled with zeros

In [20]:
x = np.array([[1,2,3], [4,5,6]], dtype=np.int)
np.zeros_like(x)

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_18388\3581534524.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([[1,2,3], [4,5,6]], dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0]])

## Create a numpy matrix of 4*4 integers, filled with fives

In [26]:
np.ones([4,4], dtype=np.int) * 5

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_18388\3878826747.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.ones([4,4], dtype=np.int) * 5


array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

## Given the X numpy matrix, create a new numpy with the same shape and type as X, filled with sevens.

In [29]:
x = np.array([[2,3],[6,2]], dtype=np.int)
np.ones_like(x) * 7

C:\Users\Eduardo\AppData\Local\Temp\ipykernel_18388\688853518.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([[2,3],[6,2]], dtype=np.int)


array([[7, 7],
       [7, 7]])

## Create a 3*3 identity numpy matrix with ones one the diagonal and zeros elsewhere

In [30]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## Create a numpy array, filled with 3 random integer values between 1 and 10

In [32]:
np.random.randint(10, size=3)

array([2, 5, 4])

## Create a 3x3x3 numpy matrix, filled with random float values

In [33]:
np.random.randn(3,3,3)

array([[[-0.58569569,  0.41274446, -0.01172234],
        [ 1.01385838,  0.9153932 ,  0.74184253],
        [ 0.48468421,  0.97149066,  0.44075809]],

       [[-0.43966677, -0.22217531, -0.82583735],
        [-1.21143997,  0.6488242 , -0.35132408],
        [-1.98727426, -0.36098762, -0.35414225]],

       [[ 2.48472443,  0.44752313,  0.29521632],
        [ 0.09415905, -0.92797318,  0.86311859],
        [ 0.8491921 ,  0.64421049, -0.78255546]]])

## Given the X python list convert it to an Y numpy array

In [35]:
x = [1,2,3]
print(x, type(x))

y = np.array(x)
print(y, type(y))

[1, 2, 3] <class 'list'>
[1 2 3] <class 'numpy.ndarray'>


## Given the X numpy array, make a copy and store it on Y

In [36]:
x = np.array([5,2,3], dtype = np.int)
print(x, id(x))

y = np.copy(x)
print(y, id(y))

[5 2 3] 2452485023856
[5 2 3] 2452485961648


C:\Users\Eduardo\AppData\Local\Temp\ipykernel_18388\272567285.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  x = np.array([5,2,3], dtype = np.int)


## Create a numpy array with numbers from 1 to 10

In [38]:
np.arange(10) + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Create a numpy array with the odd numbers between 1 to 10

In [39]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

## Create a numpy array with numbers from 1 to 10, in descending order

In [40]:
np.arange(1, 11)[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1])

## Create a 3*3 numpy matrix, filled with values ranging from 0 to 8

In [41]:
np.arange(9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## Show the memory size of the given Z numpy matrix

In [43]:
z = np.zeros((10, 10))
print('%d bytes' % (z.size * z.itemsize))

800 bytes


## Array indexation

## Given the x numpy array, show it's first element

In [44]:
x = np.array(['A', 'B', 'C', 'D', 'E'])
x[0]

'A'

## Given the x numpy array, show it's last element

In [45]:
x = np.array(['A', 'B', 'C', 'D', 'E'])
x[-1]

'E'

## Given the x numpy array, show it's first three elements

In [46]:
x = np.array(['A', 'B', 'C', 'D', 'E'])
x[0:3]

array(['A', 'B', 'C'], dtype='<U1')

## Given the x numpy array, show all middle elements

In [48]:
x = np.array(['A', 'B', 'C', 'D', 'E'])
x[1:-1]

array(['B', 'C', 'D'], dtype='<U1')

## Given the x numpy array, show the elements in reverse position

In [50]:
x = np.array(['A', 'B', 'C', 'D', 'E'])
x[::-1]

array(['E', 'D', 'C', 'B', 'A'], dtype='<U1')

## Given the x numpy array, show the elements in an odd position

In [51]:
x = np.array(['A', 'B', 'C', 'D', 'E'])
x[::2]

array(['A', 'C', 'E'], dtype='<U1')

## Given the x numpy matrix, show the first row elements

In [62]:
x = np.array([
    [1,2],
    [3,4],
    [5,6]
])
x[0]

array([1, 2])

## Given the x numpy matrix, show the last row elements

In [64]:
x = np.array([
    [1,2,3,4],
    [2,3,4,5],
    [3,4,5,6]
])
x[-1]

array([3, 4, 5, 6])

## Given the numpy matrix, show the first element on first row

In [65]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
x[0,0]

1

## Given the x numpy matrix, show the last element on last row

In [66]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])
x[-1, -1]

12

## Given the x numpy matrix, show the middle row elements

In [68]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
x[1:-1]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

## Given the x numpy matrix, show the first two elements on the first two rows

In [69]:
x = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12],
    [13,14,15,16]
])
x[0:2,0:2]

array([[1, 2],
       [5, 6]])